<#
.SYNOPSIS
    Pester 5 tests for Update-Dashboard.ps1 — deterministic markdown dashboard generator.
#>

BeforeAll {
    $repoRoot = Split-Path $PSScriptRoot -Parent
    Import-Module (Join-Path $repoRoot 'scheduler/lib/CronAgents.psd1') -Force
    Import-Module (Join-Path $PSScriptRoot 'TestHelpers.psm1') -Force

    $script:DashboardScript = Join-Path $repoRoot 'scheduler\Update-Dashboard.ps1'

    function New-TestRun {
        param(
            [string]$RunsRoot,
            [string]$AgentId,
            [string]$AgentName,
            [datetime]$Timestamp,
            [int]$ExitCode       = 0,
            [bool]$TimedOut      = $false,
            [int]$RetryAttempt   = 0,
            [bool]$FeedbackProcessed = $false,
            [string]$FeedbackContent,
            [string]$SummaryContent,
            [string]$Prompt = 'Test prompt for the agent run'
        )

        $tsStr = $Timestamp.ToUniversalTime().ToString('yyyyMMddTHHmmss')
        $nonce = '{0:x4}' -f (Get-Random -Maximum 65535)
        $dirName = "${tsStr}_${AgentId}_${nonce}"
        $runDir  = Join-Path $RunsRoot $dirName
        New-Item -Path $runDir -ItemType Directory -Force | Out-Null

        $startTime = $Timestamp
        $endTime   = $Timestamp.AddMinutes(3).AddSeconds(42)

        $meta = [ordered]@{
            agentId           = $AgentId
            agentName         = $AgentName
            prompt            = $Prompt
            startTime         = $startTime.ToString('yyyy-MM-ddTHH:mm:ss')
            endTime           = $endTime.ToString('yyyy-MM-ddTHH:mm:ss')
            exitCode          = $ExitCode
            timedOut          = $TimedOut
            retryAttempt      = $RetryAttempt
            feedbackProcessed = $FeedbackProcessed
        }
        $meta | ConvertTo-Json -Depth 10 | Set-Content -Path (Join-Path $runDir 'meta.json') -Encoding UTF8

        if ($FeedbackContent) {
            Set-Content -Path (Join-Path $runDir 'feedback.md') -Value $FeedbackContent -Encoding UTF8
        }
        else {
            $stub = "<!-- Feedback for agent run: $AgentId -->`n"
            Set-Content -Path (Join-Path $runDir 'feedback.md') -Value $stub -Encoding UTF8
        }

        if ($SummaryContent) {
            Set-Content -Path (Join-Path $runDir 'summary.md') -Value $SummaryContent -Encoding UTF8
        }

        return $runDir
    }
}

# ===== Dashboard generation =====

Describe 'Update-Dashboard' {
    Context 'With no runs' {
        BeforeAll {
            $emptyRepoRoot = Join-Path $TestDrive 'empty-repo'
            $emptyRunsRoot = Join-Path $emptyRepoRoot '.cronstate\runs'
            $emptyOutput   = Join-Path $emptyRepoRoot 'dashboard.md'
            New-Item -Path $emptyRunsRoot -ItemType Directory -Force | Out-Null

            & $script:DashboardScript -RepoRoot $emptyRepoRoot -RunsRoot $emptyRunsRoot -OutputPath $emptyOutput
            $script:EmptyDashboard = Get-Content -LiteralPath $emptyOutput -Raw -Encoding UTF8
        }

        It 'Creates the dashboard file' {
            Test-Path $emptyOutput | Should -Be $true
        }

        It 'Contains the correct header' {
            $script:EmptyDashboard | Should -Match '# CronAgents Dashboard'
        }

        It 'Contains auto-generated notice' {
            $script:EmptyDashboard | Should -Match 'Auto-generated by CronAgents'
        }

        It 'Contains Last updated timestamp' {
            $script:EmptyDashboard | Should -Match 'Last updated: \d{4}-\d{2}-\d{2}T'
        }

        It 'Has summary table with correct columns' {
            $script:EmptyDashboard | Should -Match '\| Agent \| Last Run \| Status \| Questions \| Feedback \| Detail \|'
        }

        It 'Shows no-runs placeholder in summary table' {
            $script:EmptyDashboard | Should -Match 'No runs recorded'
        }

        It 'Shows no-runs message in recent runs section' {
            $script:EmptyDashboard | Should -Match 'No runs recorded yet'
        }
    }

    Context 'With successful run' {
        BeforeAll {
            $successRepo = Join-Path $TestDrive 'success-repo'
            $successRuns = Join-Path $successRepo '.cronstate\runs'
            $successOut  = Join-Path $successRepo 'dashboard.md'
            New-Item -Path $successRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $successRepo -AgentId 'code-review' -Name 'Code Review'
            New-TestRun -RunsRoot $successRuns `
                        -AgentId 'code-review' `
                        -AgentName 'Code Review' `
                        -Timestamp ([datetime]::UtcNow.AddHours(-2)) `
                        -ExitCode 0 `
                        -SummaryContent 'Reviewed 5 files with no critical issues found.'

            & $script:DashboardScript -RepoRoot $successRepo -RunsRoot $successRuns -OutputPath $successOut
            $script:SuccessDash = Get-Content -LiteralPath $successOut -Raw -Encoding UTF8
        }

        It 'Shows success icon in summary' {
            $script:SuccessDash | Should -Match ([char]0x2705)
        }

        It 'Shows agent name in summary table' {
            $script:SuccessDash | Should -Match 'Code Review'
        }

        It 'Shows summary snippet in detail column' {
            $script:SuccessDash | Should -Match 'Reviewed 5 files'
        }

        It 'Includes duration in recent run section' {
            $script:SuccessDash | Should -Match '\*\*Duration:\*\*'
            $script:SuccessDash | Should -Match '3m 42s'
        }

        It 'Shows Success status in recent run section' {
            $script:SuccessDash | Should -Match '\*\*Status:\*\* Success'
        }

        It 'Includes links to feedback and session' {
            $script:SuccessDash | Should -Match '\[Feedback\]'
            $script:SuccessDash | Should -Match '\[Session\]'
        }
    }

    Context 'With failed run' {
        BeforeAll {
            $failRepo = Join-Path $TestDrive 'fail-repo'
            $failRuns = Join-Path $failRepo '.cronstate\runs'
            $failOut  = Join-Path $failRepo 'dashboard.md'
            New-Item -Path $failRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $failRepo -AgentId 'lint-check' -Name 'Lint Check'
            New-TestRun -RunsRoot $failRuns `
                        -AgentId 'lint-check' `
                        -AgentName 'Lint Check' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-30)) `
                        -ExitCode 1

            & $script:DashboardScript -RepoRoot $failRepo -RunsRoot $failRuns -OutputPath $failOut
            $script:FailDash = Get-Content -LiteralPath $failOut -Raw -Encoding UTF8
        }

        It 'Shows failure icon' {
            $script:FailDash | Should -Match ([char]0x274C)
        }

        It 'Shows Failed status' {
            $script:FailDash | Should -Match '\*\*Status:\*\* Failed'
        }

        It 'Shows "summary pending" when no summary.md' {
            $script:FailDash | Should -Match 'summary pending'
        }
    }

    Context 'With timed out run' {
        BeforeAll {
            $toRepo = Join-Path $TestDrive 'timeout-repo'
            $toRuns = Join-Path $toRepo '.cronstate\runs'
            $toOut  = Join-Path $toRepo 'dashboard.md'
            New-Item -Path $toRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $toRepo -AgentId 'slow-agent' -Name 'Slow Agent'
            New-TestRun -RunsRoot $toRuns `
                        -AgentId 'slow-agent' `
                        -AgentName 'Slow Agent' `
                        -Timestamp ([datetime]::UtcNow.AddHours(-1)) `
                        -ExitCode 1 `
                        -TimedOut $true

            & $script:DashboardScript -RepoRoot $toRepo -RunsRoot $toRuns -OutputPath $toOut
            $script:TimeoutDash = Get-Content -LiteralPath $toOut -Raw -Encoding UTF8
        }

        It 'Shows Timed Out status' {
            $script:TimeoutDash | Should -Match '\*\*Status:\*\* Timed Out'
        }
    }

    Context 'With pending feedback' {
        BeforeAll {
            $fbRepo = Join-Path $TestDrive 'feedback-repo'
            $fbRuns = Join-Path $fbRepo '.cronstate\runs'
            $fbOut  = Join-Path $fbRepo 'dashboard.md'
            New-Item -Path $fbRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $fbRepo -AgentId 'fb-agent' -Name 'Feedback Agent'
            New-TestRun -RunsRoot $fbRuns `
                        -AgentId 'fb-agent' `
                        -AgentName 'Feedback Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-10)) `
                        -ExitCode 0 `
                        -FeedbackContent "Great job on this run!`nKeep it up."

            & $script:DashboardScript -RepoRoot $fbRepo -RunsRoot $fbRuns -OutputPath $fbOut
            $script:FbDash = Get-Content -LiteralPath $fbOut -Raw -Encoding UTF8
        }

        It 'Shows pending feedback link' {
            $script:FbDash | Should -Match 'Pending'
        }
    }

    Context 'With processed feedback' {
        BeforeAll {
            $pfRepo = Join-Path $TestDrive 'processed-fb-repo'
            $pfRuns = Join-Path $pfRepo '.cronstate\runs'
            $pfOut  = Join-Path $pfRepo 'dashboard.md'
            New-Item -Path $pfRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $pfRepo -AgentId 'pf-agent' -Name 'Processed Agent'
            New-TestRun -RunsRoot $pfRuns `
                        -AgentId 'pf-agent' `
                        -AgentName 'Processed Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-5)) `
                        -ExitCode 0 `
                        -FeedbackProcessed $true `
                        -FeedbackContent 'Some feedback'

            & $script:DashboardScript -RepoRoot $pfRepo -RunsRoot $pfRuns -OutputPath $pfOut
            $script:PfDash = Get-Content -LiteralPath $pfOut -Raw -Encoding UTF8
        }

        It 'Shows processed feedback indicator' {
            $script:PfDash | Should -Match 'Processed'
        }

        It 'Links to feedback-result.md' {
            $script:PfDash | Should -Match 'feedback-result\.md'
        }
    }

    Context 'With multiple agents — sorted most recent first' {
        BeforeAll {
            $multiRepo = Join-Path $TestDrive 'multi-repo'
            $multiRuns = Join-Path $multiRepo '.cronstate\runs'
            $multiOut  = Join-Path $multiRepo 'dashboard.md'
            New-Item -Path $multiRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $multiRepo -AgentId 'agent-a' -Name 'Agent Alpha'
            New-TestAgentRegistration -RepoRoot $multiRepo -AgentId 'agent-b' -Name 'Agent Beta'
            New-TestRun -RunsRoot $multiRuns `
                        -AgentId 'agent-a' `
                        -AgentName 'Agent Alpha' `
                        -Timestamp ([datetime]::UtcNow.AddHours(-5)) `
                        -ExitCode 0 `
                        -SummaryContent 'Old run summary'

            New-TestRun -RunsRoot $multiRuns `
                        -AgentId 'agent-a' `
                        -AgentName 'Agent Alpha' `
                        -Timestamp ([datetime]::UtcNow.AddHours(-1)) `
                        -ExitCode 0 `
                        -SummaryContent 'Latest run summary for alpha'

            New-TestRun -RunsRoot $multiRuns `
                        -AgentId 'agent-b' `
                        -AgentName 'Agent Beta' `
                        -Timestamp ([datetime]::UtcNow.AddHours(-2)) `
                        -ExitCode 1

            & $script:DashboardScript -RepoRoot $multiRepo -RunsRoot $multiRuns -OutputPath $multiOut
            $script:MultiDash = Get-Content -LiteralPath $multiOut -Raw -Encoding UTF8
        }

        It 'Shows both agents in summary table' {
            $script:MultiDash | Should -Match 'Agent Alpha'
            $script:MultiDash | Should -Match 'Agent Beta'
        }

        It 'Shows latest run detail for Agent Alpha in summary' {
            $script:MultiDash | Should -Match 'Latest run summary for alpha'
        }

        It 'Contains Recent Runs heading' {
            $script:MultiDash | Should -Match '## Recent Runs'
        }

        It 'Shows all three runs in recent runs section' {
            $headings = [regex]::Matches($script:MultiDash, '### ').Count
            $headings | Should -Be 3
        }
    }

    Context 'Long prompt truncation' {
        BeforeAll {
            $truncRepo = Join-Path $TestDrive 'trunc-repo'
            $truncRuns = Join-Path $truncRepo '.cronstate\runs'
            $truncOut  = Join-Path $truncRepo 'dashboard.md'
            New-Item -Path $truncRuns -ItemType Directory -Force | Out-Null

            $longPrompt = 'A' * 200

            New-TestAgentRegistration -RepoRoot $truncRepo -AgentId 'trunc-agent' -Name 'Truncation Agent'
            New-TestRun -RunsRoot $truncRuns `
                        -AgentId 'trunc-agent' `
                        -AgentName 'Truncation Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-3)) `
                        -ExitCode 0 `
                        -Prompt $longPrompt

            & $script:DashboardScript -RepoRoot $truncRepo -RunsRoot $truncRuns -OutputPath $truncOut
            $script:TruncDash = Get-Content -LiteralPath $truncOut -Raw -Encoding UTF8
        }

        It 'Truncates prompt to 100 chars + ellipsis' {
            $script:TruncDash | Should -Match ('A' * 100 + '\.\.\.')
            $script:TruncDash | Should -Not -Match ('A' * 200)
        }
    }

    Context 'Summary line truncation in table' {
        BeforeAll {
            $sumTrRepo = Join-Path $TestDrive 'sumtr-repo'
            $sumTrRuns = Join-Path $sumTrRepo '.cronstate\runs'
            $sumTrOut  = Join-Path $sumTrRepo 'dashboard.md'
            New-Item -Path $sumTrRuns -ItemType Directory -Force | Out-Null

            $longSummary = 'B' * 200

            New-TestAgentRegistration -RepoRoot $sumTrRepo -AgentId 'sumtr-agent' -Name 'SumTr Agent'
            New-TestRun -RunsRoot $sumTrRuns `
                        -AgentId 'sumtr-agent' `
                        -AgentName 'SumTr Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-1)) `
                        -ExitCode 0 `
                        -SummaryContent $longSummary

            & $script:DashboardScript -RepoRoot $sumTrRepo -RunsRoot $sumTrRuns -OutputPath $sumTrOut
            $script:SumTrDash = Get-Content -LiteralPath $sumTrOut -Raw -Encoding UTF8
        }

        It 'Truncates summary first line to 120 chars in table' {
            $script:SumTrDash | Should -Match ('B' * 120 + '\.\.\.')
        }
    }

    Context 'Missing meta.json gracefully handled' {
        BeforeAll {
            $noMetaRepo = Join-Path $TestDrive 'nometa-repo'
            $noMetaRuns = Join-Path $noMetaRepo '.cronstate\runs'
            $noMetaOut  = Join-Path $noMetaRepo 'dashboard.md'
            New-Item -Path $noMetaRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $noMetaRepo -AgentId 'orphan-agent'
            $ts = [datetime]::UtcNow.AddHours(-1).ToUniversalTime().ToString('yyyyMMddTHHmmss')
            $dirName = "${ts}_orphan-agent_ab12"
            $runDir = Join-Path $noMetaRuns $dirName
            New-Item -Path $runDir -ItemType Directory -Force | Out-Null

            & $script:DashboardScript -RepoRoot $noMetaRepo -RunsRoot $noMetaRuns -OutputPath $noMetaOut
            $script:NoMetaDash = Get-Content -LiteralPath $noMetaOut -Raw -Encoding UTF8
        }

        It 'Does not throw and creates dashboard' {
            Test-Path $noMetaOut | Should -Be $true
        }

        It 'Shows agent id as fallback name' {
            $script:NoMetaDash | Should -Match 'orphan-agent'
        }
    }

    Context 'In-progress run (null exitCode)' {
        BeforeAll {
            $runningRepo = Join-Path $TestDrive 'running-repo'
            $runningRuns = Join-Path $runningRepo '.cronstate\runs'
            $runningOut  = Join-Path $runningRepo 'dashboard.md'
            New-Item -Path $runningRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $runningRepo -AgentId 'running-agent' -Name 'Running Agent'
            $ts = [datetime]::UtcNow.AddMinutes(-2).ToUniversalTime().ToString('yyyyMMddTHHmmss')
            $nonce = '{0:x4}' -f (Get-Random -Maximum 65535)
            $dirName = "${ts}_running-agent_${nonce}"
            $runDir = Join-Path $runningRuns $dirName
            New-Item -Path $runDir -ItemType Directory -Force | Out-Null

            # Write meta.json with null exitCode (as Initialize-RunMetadata does)
            $meta = [ordered]@{
                agentId           = 'running-agent'
                agentName         = 'Running Agent'
                prompt            = 'Do something long'
                startTime         = [datetime]::UtcNow.AddMinutes(-2).ToString('yyyy-MM-ddTHH:mm:ss')
                endTime           = $null
                exitCode          = $null
                timedOut          = $false
                retryAttempt      = 0
                feedbackProcessed = $false
            }
            $meta | ConvertTo-Json -Depth 10 | Set-Content -Path (Join-Path $runDir 'meta.json') -Encoding UTF8

            # feedback stub
            Set-Content -Path (Join-Path $runDir 'feedback.md') -Value "<!-- Feedback -->`n" -Encoding UTF8

            & $script:DashboardScript -RepoRoot $runningRepo -RunsRoot $runningRuns -OutputPath $runningOut
            $script:RunningDash = Get-Content -LiteralPath $runningOut -Raw -Encoding UTF8
        }

        It 'Shows Running status label' {
            $script:RunningDash | Should -Match '\*\*Status:\*\* Running'
        }

        It 'Shows running icon in summary table' {
            $script:RunningDash | Should -Match ([char]::ConvertFromUtf32(0x1F504))
        }

        It 'Shows dash for duration when still running' {
            $script:RunningDash | Should -Match '\*\*Duration:\*\* —'
        }

        It 'Shows agent name' {
            $script:RunningDash | Should -Match 'Running Agent'
        }
    }

    Context 'Personal repo defaults when RunsRoot is omitted' {
        BeforeAll {
            $personalRepoRoot = Join-Path $TestDrive 'dashboard-personal-repo'
            $repoRoot = Join-Path $TestDrive 'dashboard-infra-repo'
            $personalRuns = Join-Path $personalRepoRoot '.cronstate' 'runs'
            $personalStateRoot = Join-Path $personalRepoRoot '.cronstate'
            $outputPath = Join-Path $repoRoot 'dashboard.md'
            New-Item -Path $personalRuns -ItemType Directory -Force | Out-Null
            New-Item -Path $repoRoot -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $repoRoot -AgentId 'personal-run-agent' -Name 'Personal Run Agent'
            New-TestAgentRegistration -RepoRoot $personalRepoRoot -AgentId 'personal-run-agent' -Name 'Personal Run Agent'
            New-TestRun -RunsRoot $personalRuns `
                        -AgentId 'personal-run-agent' `
                        -AgentName 'Personal Run Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-4)) `
                        -ExitCode 0 `
                        -SummaryContent 'Personal repo run summary'

            Save-AgentQuestions -StateRoot $personalStateRoot -AgentId 'personal-run-agent' -RunId 'test-run' `
                -Questions @(@{ id = 'q1'; question = 'Use personal repo roots?'; choices = @(); recommended = $null; context = $null })

            & $script:DashboardScript -RepoRoot $repoRoot -PersonalRepoPath $personalRepoRoot -OutputPath $outputPath
            $script:PersonalDefaultDash = Get-Content -LiteralPath $outputPath -Raw -Encoding UTF8
        }

        It 'Loads run history from the personal repo by default' {
            $script:PersonalDefaultDash | Should -Match 'Personal Run Agent'
            $script:PersonalDefaultDash | Should -Match 'Personal repo run summary'
        }

        It 'Uses the same personal state root for pending questions' {
            $script:PersonalDefaultDash | Should -Match '1 pending'
            Test-Path (Join-Path $TestDrive 'dashboard-infra-repo' 'questions.md') | Should -Be $true
        }
    }

    Context 'Summary with attention frontmatter' {
        BeforeAll {
            $attRepo = Join-Path $TestDrive 'attention-repo'
            $attRuns = Join-Path $attRepo '.cronstate\runs'
            $attOut  = Join-Path $attRepo 'dashboard.md'
            New-Item -Path $attRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $attRepo -AgentId 'music-monitor' -Name 'Music Monitor'

            $attSummary = "---`nattention: true`nheadline: `"New Taylor Swift album released!`"`n---`nDetected new album release from monitored artist."

            New-TestRun -RunsRoot $attRuns `
                        -AgentId 'music-monitor' `
                        -AgentName 'Music Monitor' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-10)) `
                        -ExitCode 0 `
                        -SummaryContent $attSummary

            & $script:DashboardScript -RepoRoot $attRepo -RunsRoot $attRuns -OutputPath $attOut
            $script:AttDash = Get-Content -LiteralPath $attOut -Raw -Encoding UTF8
        }

        It 'Shows Needs Attention section' {
            $script:AttDash | Should -Match 'Needs Attention'
        }

        It 'Shows the headline in the attention section' {
            $script:AttDash | Should -Match 'New Taylor Swift album released!'
        }

        It 'Shows agent name in the attention section' {
            $script:AttDash | Should -Match 'Music Monitor'
        }

        It 'Uses headline in the detail column of the summary table' {
            $script:AttDash | Should -Match 'New Taylor Swift album released!'
        }

        It 'Shows attention callout in the Recent Runs section' {
            $script:AttDash | Should -Match 'This run needs your attention'
        }

        It 'Shows the summary body without frontmatter in Recent Runs' {
            $script:AttDash | Should -Match 'Detected new album release'
            $script:AttDash | Should -Not -Match 'attention: true'
        }
    }

    Context 'Summary without attention flag (no attention section)' {
        BeforeAll {
            $noAttRepo = Join-Path $TestDrive 'no-attention-repo'
            $noAttRuns = Join-Path $noAttRepo '.cronstate\runs'
            $noAttOut  = Join-Path $noAttRepo 'dashboard.md'
            New-Item -Path $noAttRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $noAttRepo -AgentId 'health-check' -Name 'Health Check'

            $noAttSummary = "---`nattention: false`nheadline: `"Routine check complete`"`n---`nAll systems nominal."

            New-TestRun -RunsRoot $noAttRuns `
                        -AgentId 'health-check' `
                        -AgentName 'Health Check' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-5)) `
                        -ExitCode 0 `
                        -SummaryContent $noAttSummary

            & $script:DashboardScript -RepoRoot $noAttRepo -RunsRoot $noAttRuns -OutputPath $noAttOut
            $script:NoAttDash = Get-Content -LiteralPath $noAttOut -Raw -Encoding UTF8
        }

        It 'Does not show Needs Attention section' {
            $script:NoAttDash | Should -Not -Match 'Needs Attention'
        }

        It 'Uses headline in the detail column' {
            $script:NoAttDash | Should -Match 'Routine check complete'
        }

        It 'Shows body without frontmatter in Recent Runs' {
            $script:NoAttDash | Should -Match 'All systems nominal'
            $script:NoAttDash | Should -Not -Match 'attention: false'
        }
    }

    Context 'Legacy summary without frontmatter (backwards compatibility)' {
        BeforeAll {
            $legRepo = Join-Path $TestDrive 'legacy-repo'
            $legRuns = Join-Path $legRepo '.cronstate\runs'
            $legOut  = Join-Path $legRepo 'dashboard.md'
            New-Item -Path $legRuns -ItemType Directory -Force | Out-Null

            New-TestAgentRegistration -RepoRoot $legRepo -AgentId 'legacy-agent' -Name 'Legacy Agent'
            New-TestRun -RunsRoot $legRuns `
                        -AgentId 'legacy-agent' `
                        -AgentName 'Legacy Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-3)) `
                        -ExitCode 0 `
                        -SummaryContent 'Reviewed 5 files with no critical issues found.'

            & $script:DashboardScript -RepoRoot $legRepo -RunsRoot $legRuns -OutputPath $legOut
            $script:LegDash = Get-Content -LiteralPath $legOut -Raw -Encoding UTF8
        }

        It 'Does not show Needs Attention section for legacy summaries' {
            $script:LegDash | Should -Not -Match 'Needs Attention'
        }

        It 'Shows summary content in detail column' {
            $script:LegDash | Should -Match 'Reviewed 5 files'
        }

        It 'Shows full summary in Recent Runs' {
            $script:LegDash | Should -Match 'Reviewed 5 files with no critical issues found'
        }
    }

    Context 'Runs for deleted/unregistered agents are hidden (issue #90)' {
        BeforeAll {
            $delRepo = Join-Path $TestDrive 'deleted-agent-repo'
            $delRuns = Join-Path $delRepo '.cronstate\runs'
            $delOut  = Join-Path $delRepo 'dashboard.md'
            New-Item -Path $delRuns -ItemType Directory -Force | Out-Null

            # Register only 'active-agent'; 'deleted-agent' has no registration
            New-TestAgentRegistration -RepoRoot $delRepo -AgentId 'active-agent' -Name 'Active Agent'

            # Create a run for the registered agent
            New-TestRun -RunsRoot $delRuns `
                        -AgentId 'active-agent' `
                        -AgentName 'Active Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-5)) `
                        -ExitCode 0 `
                        -SummaryContent 'Active agent completed successfully.'

            # Create a run for the deleted/unregistered agent with attention flag
            $delSummary = "---`nattention: true`nheadline: `"Stale alert from deleted agent`"`n---`nThis should not appear."
            New-TestRun -RunsRoot $delRuns `
                        -AgentId 'deleted-agent' `
                        -AgentName 'Deleted Agent' `
                        -Timestamp ([datetime]::UtcNow.AddMinutes(-3)) `
                        -ExitCode 1 `
                        -SummaryContent $delSummary

            & $script:DashboardScript -RepoRoot $delRepo -RunsRoot $delRuns -OutputPath $delOut
            $script:DelDash = Get-Content -LiteralPath $delOut -Raw -Encoding UTF8
        }

        It 'Shows the registered agent in the dashboard' {
            $script:DelDash | Should -Match 'Active Agent'
        }

        It 'Hides runs from the unregistered agent' {
            $script:DelDash | Should -Not -Match 'Deleted Agent'
        }

        It 'Does not show attention banner for deleted agent' {
            $script:DelDash | Should -Not -Match 'Needs Attention'
            $script:DelDash | Should -Not -Match 'Stale alert from deleted agent'
        }

        It 'Shows only one run in recent runs section' {
            $headings = [regex]::Matches($script:DelDash, '### ').Count
            $headings | Should -Be 1
        }
    }
}
